"""
Agent 4 — Report Synthesizer.

Combines the outputs of all three prior agents into a structured,
highly-detailed pitch-readiness report in a single JSON payload.
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
import os

import google.generativeai as genai

from pipeline.state import PipelineState
from utils.json_cleaner import clean_and_parse_json

logger = logging.getLogger(__name__)

_MODEL_NAME = "gemini-flash-latest"
_MAX_TOKENS = 8192 # Increased to support much longer reports

_SYSTEM_PROMPT = """\
You are an elite investment analyst writing a comprehensive pitch readiness assessment.
Your goal is to provide deep, actionable insights that a founder cannot get anywhere else.

Combine the inputs into a clean, structured report with four major sections.
Return only valid JSON in this exact shape:

{
  "detailed_analysis": "...",
  "assumption_map": [
     { "assumption": "...", "risk": "high|medium|low", "why": "..." }
  ],
  "blind_spots": [
     { "issue": "...", "severity": "critical|warning", "mitigation": "..." }
  ],
  "hard_questions": [
     { "question": "...", "why_it_matters": "..." }
  ],
  "sharpening_prompts": [
     { "label": "...", "prompt": "..." }
  ]
}

- `detailed_analysis`: A multi-paragraph qualitative summary (300-500 words) of the pitch's strengths, weaknesses, and overall market viability.
- `assumption_map`: The 8-10 most critical unproven claims. Be specific and cynical.
- `blind_spots`: 6-8 structural or market issues the founder missed.
- `hard_questions`: Include the 8 hard questions generated by the interrogator, preserving their 'why_it_matters' context.
- `sharpening_prompts`: 5 high-impact AI prompts the founder can use to improve their strategy.
"""

async def run_report_synthesizer(state: PipelineState) -> PipelineState:
    """
    Agent 4: Synthesize the full report using Gemini.
    """
    genai.configure(api_key=os.environ["GEMINI_API"])
    focus_area = state.get("focus_area", "general")
    
    focus_instructions = {
        "general": "Provide a comprehensive, balanced assessment across all areas of the business.",
        "technical": "Focus heavily on the technical feasibility, product roadmap, IP, and engineering challenges. Look for 'smoke and mirrors' in the tech stack.",
        "financial": "Focus heavily on the unit economics, revenue projections, burn rate, and capital efficiency. Drill into the numbers and look for unrealistic growth assumptions.",
        "market": "Focus heavily on the market size (TAM/SAM/SOM), competitive landscape, and customer acquisition strategy. Look for reasons why the market might be smaller or more crowded than claimed."
    }
    
    current_focus_instruction = focus_instructions.get(focus_area, focus_instructions["general"])

    model = genai.GenerativeModel(
        model_name=_MODEL_NAME,
        system_instruction=_SYSTEM_PROMPT + f"\n\nPRIMARY STRATEGIC FOCUS: {current_focus_instruction}"
    )

    # Combine context from all previous agents
    context = (
        f"VERTICAL: {state.get('vertical')}\n\n"
        f"STRUCTURED DATA:\n{json.dumps(state.get('structured'), indent=2)}\n\n"
        f"HARD QUESTIONS:\n{json.dumps(state.get('hard_questions'), indent=2)}\n\n"
        f"ASSUMPTIONS:\n{json.dumps(state.get('assumptions'), indent=2)}"
    )

    start = time.perf_counter()
    try:
        response = await model.generate_content_async(
            context,
            generation_config=genai.GenerationConfig(
                max_output_tokens=_MAX_TOKENS,
                response_mime_type="application/json",
            )
        )
    except Exception as exc:
        logger.error("[report_synthesizer] Gemini API failed: %s", exc)
        raise RuntimeError(f"[report_synthesizer] Gemini API failed: {exc}")

    elapsed_ms = int((time.perf_counter() - start) * 1000)
    raw_content = response.text

    try:
        report = clean_and_parse_json(raw_content)
        # Basic validation
        for required_key in ("assumption_map", "blind_spots", "sharpening_prompts", "hard_questions", "detailed_analysis"):
            if required_key not in report:
                if isinstance(report, dict):
                    report[required_key] = [] if required_key != "detailed_analysis" else "Detailed analysis generation failed."
    except Exception as exc:
        raise ValueError(
            f"[report_synthesizer] JSON parse failed: {exc}\nRaw: {raw_content[:300]}"
        ) from exc

    token_counts = dict(state.get("token_counts") or {})
    latencies_ms = dict(state.get("latencies_ms") or {})
    
    usage = response.usage_metadata
    token_counts["agent_4"] = usage.total_token_count
    latencies_ms["agent_4"] = elapsed_ms

    return {
        **state,
        "report": report,
        "token_counts": token_counts,
        "latencies_ms": latencies_ms,
    }
